### ISSUE TITLE
Experiments TODO List

### ISSUE THREAD

**Issue by ymahlau** [ymahlau/real_time_rl_project#2]
1. - [x] Acrobot-v1 (max_steps 100000, eval every 500 steps)
       1. - [x] Vanilla SAC (seed 0-4)
       2. - [x] Vanllia RTAC (seed 0-4)
       3. - [x] Vanlla SAC in RTMDP (seed 0-4)
2. - [x] CartPole-v1 (max_steps 100000, eval every 500 steps, number of iterations per eval: 20)
       1. - [x] Vanilla SAC (seed 0-4)
       2. - [x] Vanllia RTAC (seed 0-4)
       3. - [x] Vanlla SAC in RTMDP (seed 0-4)
       4. - [x] SAC in RTMDP with Output Normalization (seed 0-4)
       5. - [x] RTAC with Output Normalization (seed 0-4)
       6. - [x] SAC in RTMDP with Double Value (seed 0-4)
       7. - [x] RTAC with Double Value (seed 0-4)
       8. - [x] SAC in RTMDP with Target Network (seed 0-4)
       9. - [x] RTAC with  Target Network (seed 0-4)
       10. - [x] RTAC with shared Parameters (seed 0-4)
3. - [x] LunarLander-v2 (max_steps 300000, eval every 500 steps)
       1. - [x] Vanilla SAC (seed 0-4)
       2. - [x] Vanllia RTAC (seed 0-4)
       3. - [x] Vanlla SAC in RTMDP (seed 0-4)
       4. - [x] SAC in RTMDP with Output Normalization (seed 0-4)
       5. - [x] RTAC with Output Normalization (seed 0-4)
       6. - [x] SAC in RTMDP with Double Value (seed 0-4)
       7. - [x] RTAC with Double Value (seed 0-4)
       8. - [x] SAC in RTMDP with Target Network (seed 0-4)
       9. - [x] RTAC with  Target Network (seed 0-4)
       10. - [x] RTAC with shared Parameters (seed 0-4)
       11. - [x] RTAC with everything (seed 0-4)
       12. - [x] SAC with everything (seed 0-4)
       13. - [x] SAC in RTMDP with everything (seed 0-4)
4. - [x] RTAC shared + normalization
       1. - [x] LunarLander
       2. - [x] CartPole
5. - [x] LunarLanderStepSize (All Vanilla Versions)
       1. - [x]  RTAC 
             1.  [x]  step_size 1, train for 100000, eval every 1000 (seed 0-2)
             3.  [x] step size 0.3, train for 100000, eval every 1000 (seed 0-2)
             4.  [x] step size 0.1, train for 100000, eval every 1000 (seed 0-2)
             5.  [x] step size 0.03, train for 100000, eval every 1000 (seed 0-2)
             6.  [x] step size 0.01, train for 100000, eval every 1000 (seed 0-2)
       7. - [x] SAC in RTMDP 
             1.  [x]  step_size 1, train for 100000, eval every 1000 (seed 0-2)
             3.  [x] step size 0.3, train for 100000, eval every 1000 (seed 0-2)
             4.  [x] step size 0.1, train for 100000, eval every 1000 (seed 0-2)
             5.  [x] step size 0.03, train for 100000, eval every 1000 (seed 0-2)
             6.  [x] step size 0.01, train for 100000, eval every 1000 (seed 0-2)
       8. - [x]  SAC
             1.  [x]  step_size 1, train for 100000, eval every 1000 (seed 0-2)
             3.  [x] step size 0.3, train for 100000, eval every 1000 (seed 0-2)
             4.  [x] step size 0.1, train for 100000, eval every 1000 (seed 0-2)
             5.  [x] step size 0.03, train for 100000, eval every 1000 (seed 0-2)
             6.  [x] step size 0.01, train for 100000, eval every 1000 (seed 0-2)
